import fs from "node:fs";
import path from "node:path";

const elements = [
  "a", "abbr", "address", "article", "aside", "audio", "b", "blockquote", "button",
  "canvas", "caption", "cite", "code", "dd", "del", "details", "dfn", "dialog",
  "div", "dl", "dt", "em", "fieldset", "figcaption", "figure", "footer", "form",
  "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "hr", "i", "img",
  "input", "ins", "kbd", "label", "legend", "li", "main", "mark", "nav",
  "ol", "p", "picture", "pre", "progress", "q", "section", "select", "small",
  "span", "strong", "sub", "summary", "sup", "table", "tbody", "td", "textarea",
  "tfoot", "th", "thead", "time", "tr", "ul", "video",
];

const escapeName = (name: string): string => {
  const reserved = ["open", "type", "rec", "mod", "let", "in", "for", "while"];
  return reserved.includes(name) ? `_${name}` : name;
};

const generateBindings = (): string => {
  const bindings = elements
    .map((el) => {
      const name = escapeName(el);
      return `  @module("@styled-cva/react") @scope("default")\n  external ${name}: string => React.component<styledProps> = "${el}"\n\n  @module("@styled-cva/react") @scope("default")\n  external ${name}WithConfig: (string, 'config) => React.component<styledProps> = "${el}"`;
    })
    .join("\n\n");

  return `// StyledCva.res - Codegenerated ReScript v12 Bindings for @styled-cva/react
// Auto-generated by scripts/generate.ts. DO NOT EDIT DIRECTLY.

type styledProps = {
  className?: string,
  children?: React.element,
  onClick?: JsxEvent.Mouse.t => unit,
  href?: string,
  target?: string,
  rel?: string,
}

@module("@styled-cva/react") @variadic
external cn: array<string> => string = "cn"

@module("@styled-cva/react")
external cva: (string, 'config) => ('props => string) = "cva"

module Tw = {
${bindings}

  @module("@styled-cva/react")
  external custom: (React.component<'props>, string) => React.component<styledProps> = "default"

  @module("@styled-cva/react")
  external customWithConfig: (React.component<'props>, string, 'config) => React.component<styledProps> = "default"
}
`;
};

const main = () => {
  const outputPath = path.join(process.cwd(), "src", "StyledCva.res");
  const content = generateBindings();
  fs.writeFileSync(outputPath, content, "utf8");
  console.log(`✅ Generated ${elements.length} HTML element bindings in ${outputPath}`);
};

main();
